### ISSUE TITLE
How did you make this gif?

### ISSUE THREAD

**Issue by ghost** [Raymo111/Raymo111#3]

**Comment by Raymo111** [comment]
With Vue.js. See the "cool things that went into project" section.

**Comment by ghost** [comment]
I get that, but how did you convert it to gif format?

**Comment by PulsatingGenius** [comment]
Why am i getting this?

**Comment by Raymo111** [comment]
@dart-coder I screen-recorded it into a GIF.

**Comment by Raymo111** [comment]
@PulsatingGenius because you're "watching" this repo. That means that you are notified of all conversations. To "unsubscribe" click unwatch in the top right.

**Comment by PulsatingGenius** [comment]
Good lord I don't even use reddit

**Comment by Raymo111** [comment]
@PulsatingGenius Erm... this is GitHub, not Reddit.

**Comment by PulsatingGenius** [comment]
Oh.
