### ISSUE TITLE
Hey I've been trying like forever

### ISSUE THREAD

**Issue by Qodestackr** [Raymo111/Raymo111#4]
I've been trying forever to grab this gif and edit. How could I achieve it. With my name in it. Wilson Gichuhi Njugia is the name.

**Comment by Qodestackr** [comment]
@Raymo111

**Comment by Raymo111** [comment]
Please don't ping me and react to your own ping, that's terrible style.

Have you visited the codesandbox link at the bottom yet? If you haven't do so, if you have and are just wondering how to make it a GIF, I just screen-recorded it.

**Comment by Qodestackr** [comment]
Ok thanks
